// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Todo;

namespace backend_todo_aspnet.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20211102232433_AddLookupTables")]
    partial class AddLookupTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("todo.Models.Task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<string>("date_added")
                        .HasColumnType("text")
                        .HasColumnName("date_added");

                    b.Property<string>("date_completed")
                        .HasColumnType("text")
                        .HasColumnName("date_completed");

                    b.Property<string>("task")
                        .HasColumnType("text")
                        .HasColumnName("task");

                    b.HasKey("id")
                        .HasName("pk_task");

                    b.ToTable("task");
                });
#pragma warning restore 612, 618
        }
    }
}
